version: '3'

services:
  short-nr:
    build: ./src
    image: short-nr
    container_name: short-nr
    restart: unless-stopped
    env_file:
      - src/.env
    ports:
      - 8888:8888
  
  shortdb:
    container_name: shortdb
    image: postgres:12
    env_file:
      - src/.env
    ports:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  gql:
    image: hasura/graphql-engine:v2.0.0-alpha.1
    env_file:
      - src/.env
    ports:
      - "15003:8080"
    depends_on:
      - shortdb
    restart: always
  
  yaus-broker:
    container_name: yaus-broker
    image: "docker.io/bitnami/rabbitmq:latest"
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - ./broker:/bitnami
  
  shortnr-cache:
    container_name: shortnr-cache
    restart: always
    image: redis:latest
    ports:
      - "6381:6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  shortnr-redis-commander:
    container_name: shortnr-redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:shortnr-cache:6379
    ports:
      - '8088:8081'