version: '3'

services:
  short-nr:
    image: sha256:554d34a52e665a71ebecb255061d0df15c0332132b7fc5183992dc0116f94b0e
    container_name: short-nr
    restart: unless-stopped
    ports:
      - 8888:8888
  
  shortdb:
    container_name: shortdb
    image: postgres:12
    env_file:
      - src/.env
    ports:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  gql:
    image: hasura/graphql-engine:v2.0.0-alpha.1
    ports:
      - "15003:8080"
    depends_on:
      - shortdb
    restart: always
  
  yaus-broker:
    container_name: yaus-broker
    image: "docker.io/bitnami/rabbitmq:latest"
    environment:
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - ./broker:/bitnami
  
  shortnr-cache:
    container_name: shortnr-cache
    restart: always
    image: redis:latest
    ports:
      - "6381:6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf