tasks:
  - name: YAUS Server
    init: bash ./deploy.sh

ports:
  - port: 5432
    onOpen: ignore
    visibility: public
  - port: 15003
    onOpen: ignore
    visibility: public
  - port: 4369
    onOpen: ignore
    visibility: public
  - port: 5672
    onOpen: ignore
    visibility: public
  - port: 25672
    onOpen: ignore
    visibility: public
  - port: 15672
    onOpen: ignore
    visibility: public
  - port: 8088
    onOpen: ignore
    visibility: public
  - port: 3333
    onOpen: open-browser
    visibility: public
  - port: 9229
    onOpen: ignore
    visibility: public
  - port: 6381
    onOpen: ignore
    visibility: public
